services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment: 
            - SECRET_KEY=xf5u4xn&n#lt!0r6)826k!eaoc2(k-xc)c+)7g)&45b8c*sgew
            - DEBUG=1
        volumes:
            - .:/code 
        ports:
            - 8000:8000 
        depends_on:
            - db
    db:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data/

        environment:
            POSTGRES_PASSWORD: 'postgres'
volumes: 
    postgres_data:


